name: build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    macOS-nightly:
        runs-on: macos-15
        name: macOS nightly
        steps:
            -   name: Install Swift
                uses: tayloraswift/swift-install-action@master
                with:
                    swift-prefix: "development/xcode/swift-DEVELOPMENT-SNAPSHOT-2024-10-08-a"
                    swift-id: "swift-DEVELOPMENT-SNAPSHOT-2024-10-08-a"

            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Build
                run: swift build

    macOS:
        runs-on: macos-15
        name: macOS
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Build
                run: swift build
